// March 2026 Patch Tuesday CVE Data
// Source: Microsoft Security Update Guide, CISA KEV, Cyera Research
// Date: 2026-03-10 (Patch Tuesday)

export const patchTuesdayData = {
  date: "2026-03-10",
  total_cves: 83,
  microsoft_cves: 83,
  republished_non_microsoft: 10,
  critical_count: 8,
  important_count: 75,
};

// CVE breakdown by type
export const cveByType = [
  { type: "Elevation of Privilege", count: 46, pct: 55.4, color: "#e74c3c" },
  { type: "Remote Code Execution", count: 17, pct: 20.5, color: "#e67e22" },
  { type: "Information Disclosure", count: 9, pct: 10.8, color: "#f1c40f" },
  { type: "Denial of Service", count: 6, pct: 7.2, color: "#3498db" },
  { type: "Security Feature Bypass", count: 3, pct: 3.6, color: "#9b59b6" },
  { type: "Spoofing", count: 2, pct: 2.4, color: "#1abc9c" },
];

// Notable CVEs with details
export const notableCVEs = [
  {
    id: "CVE-2026-21536",
    product: "Microsoft Devices Pricing Program",
    type: "Remote Code Execution",
    severity: "Critical",
    cvss: 9.8,
    auth_required: false,
    user_interaction: false,
    attack_vector: "Network",
    description: "Unauthenticated RCE via unrestricted file upload (CWE-434). No user interaction required.",
    in_wild: false,
    cisa_kev: false,
  },
  {
    id: "CVE-2026-26110",
    product: "Microsoft Office",
    type: "Remote Code Execution",
    severity: "Critical",
    cvss: 8.4,
    auth_required: false,
    user_interaction: false,
    attack_vector: "Network",
    description: "RCE via untrusted pointer dereference. Preview pane trigger — no file opening needed.",
    in_wild: false,
    cisa_kev: false,
  },
  {
    id: "CVE-2026-26113",
    product: "Microsoft Office",
    type: "Remote Code Execution",
    severity: "Critical",
    cvss: 8.4,
    auth_required: false,
    user_interaction: false,
    attack_vector: "Network",
    description: "RCE via type confusion. Same preview pane attack surface as CVE-2026-26110.",
    in_wild: false,
    cisa_kev: false,
  },
  {
    id: "CVE-2026-23669",
    product: "Windows Print Queue",
    type: "Remote Code Execution",
    severity: "Critical",
    cvss: 8.8,
    auth_required: false,
    user_interaction: false,
    attack_vector: "Network",
    description: "PrintNightmare-style exploit. Privileged attacker injects code via network messages.",
    in_wild: false,
    cisa_kev: false,
  },
  {
    id: "CVE-2026-26125",
    product: "Payment Orchestrator Service",
    type: "Elevation of Privilege",
    severity: "Critical",
    cvss: 8.6,
    auth_required: true,
    user_interaction: false,
    attack_vector: "Network",
    description: "Critical EoP in payment infrastructure service.",
    in_wild: false,
    cisa_kev: false,
  },
  {
    id: "CVE-2026-26144",
    product: "Microsoft Excel",
    type: "Information Disclosure",
    severity: "Critical",
    cvss: 7.5,
    auth_required: false,
    user_interaction: false,
    attack_vector: "Network",
    description: "XSS flaw enabling remote information disclosure without privileges.",
    in_wild: false,
    cisa_kev: false,
  },
  {
    id: "CVE-2026-26127",
    product: ".NET 9.0 / 10.0",
    type: "Denial of Service",
    severity: "Important",
    cvss: 7.5,
    auth_required: false,
    user_interaction: false,
    attack_vector: "Network",
    description: "DoS in .NET on Windows/macOS/Linux. Publicly disclosed before patch.",
    in_wild: false,
    cisa_kev: false,
  },
  {
    id: "CVE-2026-21262",
    product: "Windows RRAS",
    type: "Remote Code Execution",
    severity: "Critical",
    cvss: 8.0,
    auth_required: false,
    user_interaction: false,
    attack_vector: "Network",
    description: "One of three RCE flaws in Windows Routing and Remote Access Service.",
    in_wild: false,
    cisa_kev: false,
  },
  // CISA KEV additions (March 13, 2026)
  {
    id: "CVE-2026-3909",
    product: "Chromium / Skia",
    type: "Remote Code Execution",
    severity: "Critical",
    cvss: 9.1,
    auth_required: false,
    user_interaction: true,
    attack_vector: "Network",
    description: "Out-of-bounds write in Skia 2D graphics library. Added to CISA KEV March 13.",
    in_wild: true,
    cisa_kev: true,
  },
  {
    id: "CVE-2026-3910",
    product: "Chromium V8 Engine",
    type: "Remote Code Execution",
    severity: "Critical",
    cvss: 9.3,
    auth_required: false,
    user_interaction: true,
    attack_vector: "Network",
    description: "Actively exploited flaw in V8 JavaScript engine. Sandbox escape risk. CISA KEV.",
    in_wild: true,
    cisa_kev: true,
  },
  // n8n critical vulnerability
  {
    id: "CVE-2026-21858",
    product: "n8n Workflow Automation",
    type: "Remote Code Execution",
    severity: "Critical",
    cvss: 10.0,
    auth_required: false,
    user_interaction: false,
    attack_vector: "Network",
    description: "Unauthenticated RCE in n8n. ~100,000 servers exposed globally. CVSS 10.0.",
    in_wild: true,
    cisa_kev: false,
  },
  // VMware
  {
    id: "CVE-2026-22719",
    product: "Broadcom VMware Aria Operations",
    type: "Remote Code Execution",
    severity: "Critical",
    cvss: 9.2,
    auth_required: false,
    user_interaction: false,
    attack_vector: "Network",
    description: "Command injection in VMware Aria. CISA KEV. Unauthenticated RCE.",
    in_wild: true,
    cisa_kev: true,
  },
  // Cisco
  {
    id: "CVE-2026-20127",
    product: "Cisco Catalyst SD-WAN",
    type: "Security Feature Bypass",
    severity: "Critical",
    cvss: 9.8,
    auth_required: false,
    user_interaction: false,
    attack_vector: "Network",
    description: "Authentication bypass. Remote unauthenticated attacker gets high-privilege access.",
    in_wild: true,
    cisa_kev: false,
  },
  // Android
  {
    id: "CVE-2026-0006",
    product: "Android System",
    type: "Remote Code Execution",
    severity: "Critical",
    cvss: 9.0,
    auth_required: false,
    user_interaction: false,
    attack_vector: "Network",
    description: "Critical RCE in Android System component. March 2026 Security Bulletin.",
    in_wild: false,
    cisa_kev: false,
  },
];

// Weekly CVE publication trend (illustrative, March 2026)
export const weeklyTrend = [
  { week: "Mar 2", total: 124, critical: 4 },
  { week: "Mar 9", total: 187, critical: 8 },
  { week: "Mar 10", total: 83, critical: 8 },  // Patch Tuesday
  { week: "Mar 13", total: 42, critical: 3 },  // CISA KEV additions
  { week: "Mar 15", total: 31, critical: 2 },
];
